### ISSUE TITLE
Bus error on Raspberry Pi with 3.9.0

### ISSUE THREAD

**Issue by tsantzi** [mavlink/MAVSDK#2639]
As per the title, I get a bus error on a Raspberry Pi armhf. Installed via release .deb.

Running under gdb gives:

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
[02:48:16|Info ] MAVSDK version: v3.9.0 (mavsdk_impl.cpp:32)
[New Thread 0xf7146400 (LWP 3085)]
[New Thread 0xf6945400 (LWP 3086)]
Connecting...
[02:48:16|Warn ] Connection using tcp:// is deprecated, please use tcpin:// or tcpout:// (cli_arg.cpp:41)
[New Thread 0xf5fff400 (LWP 3087)]
Waiting for system...
[02:48:16|Debug] New system ID: 1 Comp ID: 1 (mavsdk_impl.cpp:953)
[New Thread 0xf55ff400 (LWP 3088)]
[New Thread 0xf4dfe400 (LWP 3089)]
[02:48:16|Debug] Component Autopilot (1) added. (system_impl.cpp:473)

Thread 4 "main" received signal SIGBUS, Bus error.
[Switching to Thread 0xf5fff400 (LWP 3087)]
0xf7acbd54 in float mav::Message::_readSingle<float>(mav::Field const&, int) const () from /lib/libmavsdk.so.3
```

Works fine after downgrading to 3.8.1 (and 2.13.0 that I was using before that)

**Comment by julianoes** [comment]
Can you get me the backtrace at that moment?

**Comment by tsantzi** [comment]
Sure, here you go:

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
[07:46:04|Info ] MAVSDK version: v3.9.0 (mavsdk_impl.cpp:32)
[New Thread 0xf7146400 (LWP 22270)]
[New Thread 0xf6945400 (LWP 22271)]
Connecting...
[07:46:05|Warn ] Connection using tcp:// is deprecated, please use tcpin:// or tcpout:// (cli_arg.cpp:41)
[New Thread 0xf5fff400 (LWP 22272)]
[07:46:05|Debug] New system ID: 1 Comp ID: 1 (mavsdk_impl.cpp:953)
[New Thread 0xf55ff400 (LWP 22273)]
[New Thread 0xf4dfe400 (LWP 22274)]
[07:46:05|Debug] Component Autopilot (1) added. (system_impl.cpp:473)
Waiting for system...

Thread 4 "main" received signal SIGBUS, Bus error.
[Switching to Thread 0xf5fff400 (LWP 22272)]
0xf7acbd54 in float mav::Message::_readSingle<float>(mav::Field const&, int) const () from /lib/libmavsdk.so.3
(gdb) bt
#0  0xf7acbd54 in float mav::Message::_readSingle<float>(mav::Field const&, int) const () from /lib/libmavsdk.so.3
#1  0xf7ac8604 in mav::Message::getAsNativeTypeInVariant(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const () from /lib/libmavsdk.so.3
#2  0xf7801d44 in mavsdk::LibmavReceiver::libmav_message_to_json[abi:cxx11](mav::Message const&) const () from /lib/libmavsdk.so.3
#3  0xf57ff000 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) 
```

**Comment by julianoes** [comment]
Interesting. Are you sending any custom messages? Or do you think there is an example I could use to try to reproduce this?

**Comment by julianoes** [comment]
Looks like it could be a potential alignment error on ARM where float need to be aligned by 4-byte boundaries.

**Comment by julianoes** [comment]
I tried on my RPi 5 with `arm64` but couldn't reproduce it yet. What RPi is this on, and what arch? You mention `armhf` so that would hint to an older 32bit one?

**Comment by julianoes** [comment]
Another thought, so far I had been compiling on the RPi and not used the library files which are cross compiled in dockcross, so that might also make a difference.

**Comment by tsantzi** [comment]
No custom messages. However, unfortunately the software in question is proprietary so can't share as is, but I'll try to prepare a simple test to replicate the issue.

Some more info: 

Raspberry Pi 4
OS is 32 bit armhf
Compiled on board (no cross compiler) 
gcc (Raspbian 12.2.0-14+rpi1) 12.2.0

Hope this helps!

**Comment by tsantzi** [comment]
Turns out this is all that's needed to replicate the issue: 

```
 #include <stdio.h>
 #include <iostream>
 #include <thread>
 
 #include <mavsdk/mavsdk.h>
 
 
 int main(int argc, char **argv)
 {
     mavsdk::Mavsdk mavsdk{mavsdk::Mavsdk::Configuration{mavsdk::ComponentType::CompanionComputer}};
     std::optional<std::shared_ptr<mavsdk::System>> system;
 
     printf("Connecting...\n");
     mavsdk::ConnectionResult connection_result = mavsdk.add_any_connection("tcp://127.0.0.1:5760");
     if (connection_result != mavsdk::ConnectionResult::Success)
     {
         std::cerr << "Connection failed: " << connection_result << '\n';
         exit(1);
     }
 
     printf("Waiting for system...\n");
     system = mavsdk.first_autopilot(3.0);
     if (!system)
     {
         std::cerr << "Timed out waiting for system\n";
         exit(1);
     }
 
     printf("Done\n");
 
     // Yield
     while (true)
     {
         std::this_thread::sleep_for(std::chrono::milliseconds(1000));
     }
 }
```

Works with 3.8.1, bus error with 3.9.0

**Comment by julianoes** [comment]
Are you building without cURL and OpenSSL, or what did you do about this:

```
cc1: error: '-mfloat-abi=hard': selected architecture lacks an FPU
cc1: error: '-mfloat-abi=hard': selected architecture lacks an FPU
cc1: error: '-mfloat-abi=hard': selected architecture lacks an FPU
cc1: error: '-mfloat-abi=hard': selected architecture lacks an FPU
make[1]: *** [Makefile:4951: apps/lib/libapps-lib-app_libctx.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:4959: apps/lib/libapps-lib-app_params.o] Error 1
make[1]: *** [Makefile:4967: apps/lib/libapps-lib-app_provider.o] Error 1
make[1]: *** [Makefile:4975: apps/lib/libapps-lib-app_rand.o] Error 1
make[1]: Leaving directory '/home/julian/src/MAVSDK/build-release/third_party/openssl/openssl/src/openssl-build'
make: *** [Makefile:2940: build_libs] Error 2
ninja: build stopped: subcommand failed.
```

**Comment by julianoes** [comment]
Ok, managed with `-DBUILD_WITHOUT_CURL=ON` but then I get this linking error:

```
/usr/bin/ld: src/unit_tests/CMakeFiles/unit_tests_runner.dir/__/mavsdk/core/callback_list_test.cpp.o: undefined reference to symbol '__atomic_fetch_add_8@@LIBATOMIC_1.0'
/usr/bin/ld: /lib/arm-linux-gnueabihf/libatomic.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
[189/210] Building CXX object src/system_tests/CMakeFiles/system_tests_runner.dir/camera_settings.cpp.o
ninja: build stopped: subcommand failed.
```

Looks like I needed to add `atomic` to the linked libs.

**Comment by julianoes** [comment]
Ok,  I can reproduce the issue!

**Comment by julianoes** [comment]
This will hopefully fix it: https://github.com/julianoes/libmavlike/pull/1

**Comment by julianoes** [comment]
Fix https://github.com/mavlink/MAVSDK/pull/2641 and release coming soon.
